/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'GD32F407' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "gd32f4xx.h"

/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@10.5.1 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@10.5.1 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@10.5.1 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Coroutines@10.5.1 */
#define RTE_RTOS_FreeRTOS_COROUTINE     /* RTOS FreeRTOS Co-routines */
/* ARM::RTOS&FreeRTOS:Event Groups@10.5.1 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@10.5.1 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Message Buffer@10.5.1 */
#define RTE_RTOS_FreeRTOS_MESSAGE_BUFFER /* RTOS FreeRTOS Message Buffers */
/* ARM::RTOS&FreeRTOS:Stream Buffer@10.5.1 */
#define RTE_RTOS_FreeRTOS_STREAM_BUFFER /* RTOS FreeRTOS Stream Buffers */
/* ARM::RTOS&FreeRTOS:Timers@10.5.1 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* GigaDevice::Device:StdPeripherals:DMA@3.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_DMA
/* GigaDevice::Device:StdPeripherals:EXTI@3.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_EXTI
/* GigaDevice::Device:StdPeripherals:GPIO@3.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_GPIO
/* GigaDevice::Device:StdPeripherals:MISC@3.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_MISC
/* GigaDevice::Device:StdPeripherals:PMU@3.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_PMU
/* GigaDevice::Device:StdPeripherals:RCU@3.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_RCU
/* GigaDevice::Device:StdPeripherals:SYSCFG@3.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_SYSCFG
/* GigaDevice::Device:StdPeripherals:USART@3.0.2 */
#define RTE_DEVICE_STDPERIPHERALS_USART


#endif /* RTE_COMPONENTS_H */
